# Generated by Django 2.1.7 on 2019-02-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmessage', '0002_auto_20190223_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус доставки'),
        ),
    ]
